### ISSUE TITLE
[Bug] Morphology.ome.tif low resolution after running Sopa on Xenium Sample

### ISSUE THREAD

**Issue by pakiessling** [gustaveroussy/sopa#104]
Hi Quentin,

I noticed something strange with the Xenium run I am working on.
After running sopa the image of the multimodal staining looks very bad compared to the Xenium output from the machine:

Before:
![xenium](https://github.com/user-attachments/assets/e291f46f-9b9f-4dd0-8f96-117c8f386e0f)

After:
![sopa](https://github.com/user-attachments/assets/535bdef6-3007-44ae-8a18-50d991671eb0)

This is only happening with Xenium data, Merfish stainings come out very nice.
File size before: 15.21 GB, after: 17.43 GB 

Any idea what could be happening?

**Comment by quentinblampey** [comment]
Hi @pakiessling,

Sometimes the Xenium Explorer can be a little bit buggy, have you tried to close and re-open it?
Else, have you seen any specific warning when running Sopa?

Another (and better) option is to simply not re-create this image. Indeed, since you already have the Xenium image, you don't need to create it again in Sopa. You can move/copy the Xenium image to Sopa's output directory, or add a symlink.

I already planned to update the pipeline to not re-create the image+transcript file when using Xenium data, but I haven't found time to do it yet

**Comment by pakiessling** [comment]
After closing and opening it 3 times it looks fine now 🙄 

Do you know which files I would need to replace?

I just tried to replace morphology.ome.tif from sdata.explorer with the 10x one and I could only see the nculear channel afterwards

**Comment by quentinblampey** [comment]
Hum, okay, let me know if it happens again. Normally it should be very rare, so I'm surprised that it happened 3 times before working

Do you have the recent Xenium version with the `morphology` directory?

**Comment by quentinblampey** [comment]
I'm closing the issue for now, don't hesitate to let me know if it happens again!
