### ISSUE TITLE
[Bug]Invalid element type: <class 'xarray.core.dataarray.DataArray'>

### ISSUE THREAD

**Issue by Yifan-debug** [gustaveroussy/sopa#107]
## Description
Same example dataset. Rerun the code and get new error. 
## Reproducing the issue
ValueError: Invalid element type: <class 'xarray.core.dataarray.DataArray'>

## System
 - OS: [e.g. Linux]
 - Python version [e.g. 3.9.7]
<details>
<summary>Dependencies versions</summary>
<br>
Paste here what 'pip list' gives you.
</details>

**Comment by Yifan-debug** [comment]
I find the same issue with my own dataset. Here is teh error code. ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 patches = sopa.segmentation.Patches2D(sdata, image_key, patch_width=1200, patch_overlap=50)
      2 patches.write()
      3 from sopa._sdata import get_spatial_image

File /projectnb/mylabscc/yzw0093/.conda/envs/sopa/lib/python3.10/site-packages/sopa/patches/patches.py:112, in Patches2D.__init__(self, sdata, element_name, patch_width, patch_overlap)
    110     tight, int_coords = True, False
    111 else:
--> 112     raise ValueError(f"Invalid element type: {type(self.element)}")
    114 self.patch_x = Patches1D(xmin, xmax, patch_width, patch_overlap, tight, int_coords)
    115 self.patch_y = Patches1D(ymin, ymax, patch_width, patch_overlap, tight, int_coords)

ValueError: Invalid element type: <class 'datatree.datatree.DataTree'>

**Comment by Yifan-debug** [comment]
I believe this issue is in the sopa.segmentation.Patches2D. I tried with image_key, it not working. I tried with points_key, it works. but there is no spatial_image with the points_key. There do have the image in the sdata. Please check the attach screenshot. 
[sopa_error_example.md](https://github.com/user-attachments/files/16575727/sopa_error_example.md)

**Comment by quentinblampey** [comment]
Hello @Yifan-debug,
This error seems to be related to the issue https://github.com/gustaveroussy/sopa/issues/85, but it has been fixed since then. Which versions of Sopa do you use? You should have `sopa>=1.1.1` to benefit from the fix.

Also, regarding your code: the Patches2D class can be used to create patches on the image (when providing image_key), or on transcript (when providing points_key). Therefore, we need to use image_key for CellPose segmentation, and points_key for transcript-based segmentation (e.g., using Baysor). Here, you are using the transcripts for CellPose segmentation, hence the error.

Hope this helps!
