### ISSUE TITLE
cell segmentation with only membrane protein

### ISSUE THREAD

**Issue by sunshx-bioinfo** [gustaveroussy/sopa#110]
Hi,

I have a image with DAPI over exposure which makes cell segmentation difficult, but membrane protein is quite clear. 

Then i try to use sopa to perform cell segmentation like below:

First time:  `sopa segmentation cellpose test.zarr/ --channels DAPI --channels CD3e --diameter 35`

Second time:  `sopa segmentation cellpose test.zarr/  --channels CD3e --diameter 35`

Both of results are poor.

It seems that sopa can perform cell segmentation with only membrane protein, but the model may be not suitable.  Is that right?

Can you give me some advice to rescue my data?

Thx

**Comment by quentinblampey** [comment]
Hi,
If CD3e is quite clear, the segmentation should be good on both (i) DAPI + CD3e and (ii) CD3e only.
Could you show me an image of the resulting boundaries overlayed on the DAPI + CD3e stainings?

Another solution: changing the parameters of Cellpose might help (although the default parameters are fine 90% of the time).
If you have one small image sample, you could run it inside cellpose (either locally or [online](https://www.cellpose.org/)) to try multiple sets of parameters. When you are satisfied, you can use these parameters inside Sopa for scalability!

**Comment by sunshx-bioinfo** [comment]
@quentinblampey Thanks for you reply!

I'll try your solution.

And here is the image of resulting boundaries with DAPI and CD3e:
![1724227612500](https://github.com/user-attachments/assets/61b81b55-a274-44de-9c2a-0b0227fa141f)

I also provide a test image if you want to try.
[test image](https://github.com/sunshx-bioinfo/picture/blob/master/codex_test.tif)

**Comment by quentinblampey** [comment]
Thanks for sending this image!

Actually, it seems to me that the issue comes from the `--diameter`. Looking at the picture you sent me, it seems that Cellpose is trying to segment cells much bigger than they actually are!

What is the technology that you use? And what is your scale factor? This will help you find the right diameter. You can also look [here](https://github.com/gustaveroussy/sopa/tree/master/workflow/config) to find the recommended diameter for each technology.

In brief, for now, don't try what I said regarding the "right set of cellpose parameters", I think is most likely due to the diameter. If it still doesn't fix it, then we can try changing the other cellpose parameters.

**Comment by sunshx-bioinfo** [comment]
This is an image from CODEX. A lot of lymphocyte cells fill in lymph gland tissue that the image shows and yes, these cells are smaller and its diameter is about 5 um.  My scale factor is about 30X. 

I'll try again with `--diameter 20`, is it suitable ?

Thank you very much!

**Comment by quentinblampey** [comment]
According to your information, I think `--diameter 15` should be a good value, but you can also try 20 indeed.
Let me know how it goes 🙂

**Comment by sunshx-bioinfo** [comment]
Hi, Sorry for late reply.

I've tried 3 different diameters, 13,15 and 20, with DAPI + CD3e or only CD3e,  you can see the image of resulting boundaries below:
![1724309800583](https://github.com/user-attachments/assets/a1c049d8-ad0b-450d-9a9f-004433975dd5)

I think there are few differences between results of diameters=13 and 15,  and their results are better than diameter=20. 

There are more cells are detected when segmenting with DAPI + CD3e then with only CD3e, but accuracy becomes lower (as showed in red rectangle area). 

Another problem is that cell boundary extends some distance, this is suitable for nuclear staining, such as DAPI, but is not nessary for membrane protein. Can we use a paramter to make the distance of extanding to be 0? And when i saw another membrane protein, CD79a, I found cells marked by it are not segmented correctly. So I use these 2 membrane proteins to cell segmenting, the result is below, as we can see, cells are overlap. If we can stop cell boundary extending, the result would be better.
![1724313409163](https://github.com/user-attachments/assets/5d65a238-bd7f-48cc-943a-757a305d7229)

**Comment by quentinblampey** [comment]
Hi, thanks for trying all this and for sending the results!
Indeed the results looks better with diameter 13 and 15.

Regarding the cell expansion, there is indeed a parameter called `expand_radius_ratio` which can be used in `sopa aggregate`, but it is 0 by default. Therefore, the overlaps you see are not due to cell expansion, but they are due to the fact that the cell segmentation round with CD3E is highly different from the segmentation round with CD79A. Therefore, when combining the two segmentations, some cells overlap. Don't you have a shared membrane staining for all cells?

One solution could be to combine the CD3E and CD79A into one channel, for instance via a `max` operation, and then run segmentation on the combined channel. But this doesn't always provide good results, it's just in case you want to try.

**Comment by sunshx-bioinfo** [comment]
Thanks for your good advice. When i use a shared membrane protein, CD45, the results are much better(below).

Pink: CD3e,  Green: CD45,  Orange: CD79a
![1724319192772](https://github.com/user-attachments/assets/c1504bfe-09b1-4da1-9a73-e24320ac93f9)

But i want to say there is a expansion around membrane staining just like around a nuclei, we can see cell overlaps however the membrane staining are not ovelapping actually.

And Thanks again for your immediate and usefull reply, my work now can going on :).

**Comment by quentinblampey** [comment]
Looking much better, indeed! I'm closing the issue :)

In the example you show, the cell radius is not expanded, we only take the output of Cellpose. Sometimes, CellPose may decide to define cells that are slightly bigger than the actual membrane staining; I think this is what you are seeing. When cell expansion is performed inside Sopa (which is possible but not the default behavior), the cell boundaries would overlap, even when doing only one segmentation round. Hope this helps!
