### ISSUE TITLE
Suggestions for documentation

### ISSUE THREAD

**Issue by pakiessling** [gustaveroussy/sopa#15]
I noticed some things while going through your (very impressive) project:

- I would suggest to edit this line https://github.com/gustaveroussy/sopa/blob/3577f9d93a82af96e8a15d3b1f4a607e017b34a2/workflow/config/example_commented.yaml#L86 to make it more clear that this is telling Sopa about the state that the reference scRNA is in and not what action should be performed on the reference, that was confusing to me

- In the Snakemake tutorial https://gustaveroussy.github.io/sopa/tutorials/snakemake/ I would also add the line 
```
# this generates a 'tuto.zarr' directory
sopa read . --sdata-path tuto.zarr --technology uniform
```
from the CLI tutorial, as the code below otherwise wont work

- In the html report you show the Per-cell intensity for every channel, but there is no legend mapping the colors in the diagram to the channels

**Comment by quentinblampey** [comment]
Hello @pakiessling,

Thanks for this very relevant advice:
- Indeed, it was not clear. I updated it, what do you think?
https://github.com/gustaveroussy/sopa/blob/67c877c37531d2c4f26c36e1d766031651d9a0fa/workflow/config/example_commented.yaml#L86
- Yes I realized this, it was fixed in a previous commit: I updated the `Snakefile` so that snakemake doesn't complain for the tutorial. The line you mentioned should not be necessary anymore. Can you try with the latest version (or pull from `master`, if you cloned the repo)?
- Good catch: I provided the legend, but my "HTML engine" was not detecting and thus not displaying the legend

Everything should be fixed in the master branch, and I will soon release a new version :)

**Comment by pakiessling** [comment]
I like it a lot!
