### ISSUE TITLE
cell id corresponds

### ISSUE THREAD

**Issue by Chuang1118** [gustaveroussy/sopa#47]
Hi, 

Following [spatialdata_xenium_explorer.write](https://github.com/quentinblampey/spatialdata_xenium_explorer/issues/5#top)#5

Like sopa has changed initial cell id by re-build Tables(Anndata) see below.

Before sopa processing:
![Screenshot from 2024-04-03 15-03-09](https://github.com/gustaveroussy/sopa/assets/52918801/c9335277-825e-4652-9df3-8b877ec0e475)
After sopa processing: 
![Screenshot from 2024-04-03 15-03-30](https://github.com/gustaveroussy/sopa/assets/52918801/6c0e8c46-21f5-4ca4-a855-49c721090c2e)

As the result file `analysis.zarr.zip`:
`[INFO] (sopa.io.explorer.table) Writing 2 cell categories: region, slide`

How to find the new cell id corresponds? I guess that's same order, but I am not sure.
Does sopa have a temporary file contains this information.

Thanks for your help.
Chuang

**Comment by quentinblampey** [comment]
Hello @Chuang1118,

Sopa indeed changes the cell IDs to be consistent with the Xenium Explorer. Yes the cell IDs should have the same order, thus you can retrieve the other columns from `obs`.

Yet, sometimes, you might have an "artefact" cell that cannot be converted to a geometry. In that case, you'll not have the same number of rows, and you will not be able to match the two dataframes (at least, not without going deeper into the source code of Sopa).
What are the columns you are interested in? All the staining intensities can be computed with Sopa, as well as everything related to the cells' areas/morphology.

**Comment by Chuang1118** [comment]
Now, I am working with raw data come from CosMx instrument to get a first impression(from rawdata to experiment.xenium). 
In effect, all datasets have been processed, e.g. quality control, cell phenotype annotation, cellular neighborhoods...
I want to visualize the cell phenotype map for example. In other words, these metadata have done by initial cell id.
>you might have an "artefact" cell that cannot be converted to a geometry. In that case, you'll not have the same number of rows, and you will not be able to match the two dataframes

Thank you for your explanation. Based on your clarification, how to address this case while having the "artefact" cell id in the middle of row names.

**Comment by quentinblampey** [comment]
The output order corresponds to the same order as the IDs inside the labels, which should be the same as the `cell_ID` column.

How did you merge the two dataframes? Looking at the screenshots you gave me, the cell areas seem consistent (there are some minor differences due to the conversion to geometries, which is expected). For instance, can you plot a scatter plot with `new_obs['area'].values` over `old_obs['Area'].values`? If we see a great correlation, the order is preserved.

Concerning the artefact cells, two solutions:
- `cells = shapes.geometrize(sdata["1_labels"].values, smooth_radius_ratio=0)` will produce the same amount of cells, except in extreme cases. Indeed, the cells not being converted to geometries is happening when smoothing a cell that is extremely thin, so setting `smooth_radius_ratio=0` should prevent the cell from being removed.
- Instead of `shapes.geometrize`, you can run the lines below. In this block of code, the `len(cells)` is guaranteed to be equal to the initial number of cells. The artefact cells will be `None`, but the order remains, so you know which `None` cell correspond to which original cell.
```python
from sopa.segmentation.shapes import _contours, _default_tolerance, _smoothen_cell

mask = sdata["1_labels"].values

max_cells = mask.max()

cells = [_contours((mask == cell_id).astype("uint8")) for cell_id in range(1, max_cells + 1)]

mean_radius = np.sqrt(np.array([cell.area for cell in cells]) / np.pi).mean()
smooth_radius = mean_radius * 0.1   # this 0.1 value cooresponds to 'smooth_radius_ratio'
tolerance = _default_tolerance(mean_radius)

cells = [_smoothen_cell(cell, smooth_radius, tolerance) for cell in cells]
```

**Comment by Chuang1118** [comment]
Hi,

It's my bad, I have made a mistake when merging two data frames.
I confirm cell id have conserved the same order both no-sopa and post-sopa processing in condition of 0% of non-geometrized cells.

>can you plot a scatter plot with new_obs['area'].values over old_obs['Area'].values?
```
new_obs = sdata.tables['table'].obs['area'].values # post-sopa
old_obs = raw_metadata['Area'].values # raw_metadata = sdata['table'].obs
plt.scatter(new_obs, old_obs)
```
![Screenshot from 2024-04-04 13-16-26](https://github.com/gustaveroussy/sopa/assets/52918801/3c815f52-78ed-4352-b01b-39ee0af1370f)
>the cell areas seem consistent (there are some minor differences due to the conversion to geometries, which is expected)

For the moment, I need give a feedback to pathologist to visualize all annotations. As you said, there are some minor changed to define cells between output CosMx instrument and post-sopa.

There are some Xenium data in my lab, evidently we will use sopa. During this time, I use directly changed ids for downstream analysis. I don't have this problem any more ;) 

Thanks a lot for your help,
Chuang

**Comment by quentinblampey** [comment]
Perfect!

Great, that sounds good for your Xenium data! Also, just in case you need stitching for a whole CosMX experiment, this will come in the next few weeks.
