### ISSUE TITLE
Overlay custom segmentation using cell segmentation resolver

### ISSUE THREAD

**Issue by EST09** [gustaveroussy/sopa#55]
Hi, 

Thank you for SOPA, it looks really helpful. I'd love to use the cell segmentation resolver. However, I'm struggling a little with how best to implement. 

I have custom segmentation for a particular cell type in H&E. I've added this as a shape to my spatialdata object in the same coordinate system as cell boundaries (the default Xenium segmentation). I'd love to overlay this custom segmentation onto the default Xenium cell segmentation (cell boundaries) so that any cells/transcripts in the default under the custom segmentation get merged into the custom segmentation but the other cells from the default are kept.  

Is there a way to do this in SOPA at all please? 

Best wishes, 
Emily

**Comment by quentinblampey** [comment]
Hello @EST09,

Thanks for your interest in Sopa. I have a few questions to ensure I understand correctly what you want to do:
1. The overall result should be one segmentation composed of your custom segmentation + the default segmentation for the other cells, right? I mean, you don't want to show both segmentation in the explorer separately, but, instead, it should be merged into one segmentation?
2. Have you already aligned your H&E data to the DAPI image? Else, you'll need to use the Xenium Explorer to align both images, because they are not in the same coordinate system by default.
3. For every cell in the resulting "resolved segmentation", I guess you want to know if it comes from the custom segmentation or from the default segmentation, right?
4. For the custom cells, do you want to aggregate the transcripts/channels inside their boundaries to have a cell-by-gene table?

In any case, this will be possible with Sopa, I'm trying to answer your question as accurately as possible!

**Comment by quentinblampey** [comment]
Thanks for providing these details! I confirm that this can be done with Sopa, but it requires combining a few different functions from the [API](https://gustaveroussy.github.io/sopa/api/segmentation/aggregate/#sopa.segmentation.aggregate.Aggregator)

I'll add a new function to make it easy to use (actually, I also need this for some of my projects, so I needed to do implement it anyway).
I'll let you know, but this shouldn't take too much time, and it will be released in `sopa==1.0.11`

**Comment by quentinblampey** [comment]
Hello @EST09, just wanted to let you know that I released `sopa==1.0.11`, which contains this feature. You can read the documentation of this function [here](https://gustaveroussy.github.io/sopa/api/segmentation/aggregate/#sopa.segmentation.aggregate.overlay_segmentation).
Concerning the Explorer update, you can refer to [this function](https://gustaveroussy.github.io/sopa/api/io/#sopa.io.write).
Hope it solves your issue :)

**Comment by quentinblampey** [comment]
Hello @EST09, is everything working as expected? Should I close the issue?

**Comment by quentinblampey** [comment]
Hi,

Indeed it's weird to have a different transcript count. Just to make sure I understand what you did: you tried the two aproaches below, right?
1. Add the shapes (as polygons) to the spatialdata object and run the `Aggregator` on these cells
2. Add the shapes (as polygons) to the spatialdata object and use the `overlay_segmentation` function

The `overlay_segmentation` function is also using the aggregator internally so it's unexpected to have different results.

Concerning your last question, no I think there is no way to prevent this for now. So, subsetting the anndata object is needed, even though it may be inconvenient, I agree...

**Comment by quentinblampey** [comment]
I'm closing this issue, but feel free to re-open if you need extra information!
