### ISSUE TITLE
[Feature] Cellpose - artificially define an area of cytoplasm

### ISSUE THREAD

**Issue by mariavigovaldoleiros** [gustaveroussy/sopa#59]
**Feature request / question**
In the absence of a general membrane marker, Sopa/cellpose (using only DAPI) will not "expand" the detected nuclei to generate an artificial cell membrane/cytoplasm area. In QuPath, cellpose is available as an extension and the code has the possibility to artificially expand the nuclei:
![image](https://github.com/gustaveroussy/sopa/assets/148148845/422fd64f-c8d6-43cf-a290-412d0087100d)

Would it be possible to pass this parameter to cellpose within Sopa? Perhaps in the config
![image](https://github.com/gustaveroussy/sopa/assets/148148845/6ef40c93-67a3-494b-ae00-34d5a58065ac)

**Output example:**
Sopa (Cell = Nuclei)
![image](https://github.com/gustaveroussy/sopa/assets/148148845/f168c4c3-a657-4d39-8a50-03ef9f38513f)

QuPath (Cell > Nuclei)
![image](https://github.com/gustaveroussy/sopa/assets/148148845/6f0b7a42-ee90-4778-9b34-356168fbbe36)

**Comment by quentinblampey** [comment]
Hello @mariavigovaldoleiros,

Actually, we can use cell radius expansion, but only to compute the channel intensity for each cell (see the `expand_radius_ratio` parameter [here](https://github.com/gustaveroussy/sopa/blob/580c8e6130f63f76792007292b403a4311a4ce58/workflow/config/example_commented.yaml#L73)). Yet, indeed, we don't display it in the Xenium Explorer.

Do you need cell expansion only to compute the intensity of membrane channels, or do you also want to visualize it on the Explorer?
If you need it in the Explorer, I'll implement it too: it should be pretty easy since the Xenium Explorer support both "Cell" and "Nucleus" boundaries.

**Comment by josenimo** [comment]
Hey @quentinblampey, 

just pitching my two cents here. 
I would like something like expand_radius_ratio that would allow me to store the expanded shapes. I use skimage.segmentation.expand_labels for my tif masks. How would that work for geojson shapes.

Second thing, would it be possible to translate the shapes after conflict resolution back into a tif labels mask? 
and store it as an image in the spatial data object?

**Comment by quentinblampey** [comment]
Hello @josenimo, these operations can actually be done easily outside of Sopa, using only the SpatialData object:

1. to expand your shapes, you can do `geo_df = sdata["cell_boundaries"].buffer(expand_radius)`, where `expand_radius` is the value used to expand the shapes (change `"cell_boundaries"` to the shapes key of your choice). Then you can store this geodataframe, for instance `sdata["new_shapes"] = geo_df`
2. to convert shapes to mask, I implemented a [`rasterize`](https://spatialdata.scverse.org/en/latest/generated/spatialdata.rasterize.html) function in SpatialData. You can also read [this tutorial](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/labels_shapes_interchangeability.html) for more details!

**Comment by quentinblampey** [comment]
Hello @mariavigovaldoleiros, did my comments answer your question? I'm closing this issue, feel free to re-open
