### ISSUE TITLE
[advice]Cellpose troubleshooting

### ISSUE THREAD

**Issue by cstrlln** [gustaveroussy/sopa#67]
I trained a cellpose model and used it with a morphology2D file outside of sopa and got pretty good results, however when running it with the same image on sopa I don't get as many cells. I think it might have to do with the image settings ( e.g. contrast, etc), and maybe the patching??

What do you suggest for troubleshooting this? I guess I can use the CLI and try different parameters there? and then move to snakemake?

Thanks

**Comment by quentinblampey** [comment]
Hello @cstrlln,

Do you use the same cellpose parameters in both cases?
Did you only check the total number of cells, or did you visually saw that Sopa was missing cells? Because Sopa does some filtering to remove artefacts (i.e., segmented cells that are too small to be a cell), so it may lead to a smaller number of cells, but since only artefacts are removed it should look good. You can check [this comment](https://gustaveroussy.github.io/sopa/faq/#cellpose-is-not-segmenting-enough-cells-what-should-i-do) in the FAQ that may help you concerning this.

In brief, you can check the following:
- make sure to use the same cellpose parameters
- check if `min_area` is not too high (note that the area is in pixels^2, and a too large value can lead to a big drop in cell number)
- have a look to the log file for the segmentation (rule called "`patch_segmentation_cellpose`" if you use the pipeline) and see how many artefact cells are removed. If you use the CLI or the API, the logs will appear in the console/terminal.
- try different values for `gaussian_sigma` and `clip_limit` (but default values usually work well, so I would not try this option first)

It's really unlikely to be due to the patching process, though.

Yes, you can use the CLI to debug this, as you'll directly see the number of cells logged in your terminal after `sopa resolve cellpose`.
I suggest performing the tests on one FOV to make it quick. I also recommend using a large patch size so that you have only one patch, it will be easier for testing purposes.

I hope this will help you!

**Comment by quentinblampey** [comment]
Not yet, but I'm thinking about adding it
So, if I add it, I'll let you know!
