### ISSUE TITLE
Filtering by qv score for Xenium datasets

### ISSUE THREAD

**Issue by saito-k1** [gustaveroussy/sopa#79]
Hello again,

I was just wondering if there was a way to filter by qv score (phred-based quality value) for Xenium datasets. The typical qv cutoff is 20; however, I noticed in my spatialdata object that the transcripts ranged from 7.6 to 40.0 so it doesn't look like it's being filtered by qv score in the pipeline. Would it be possible to add this option, or do you not recommend filtering by this value? Thank you!

**Comment by quentinblampey** [comment]
Hello @saito-k1!
Indeed we don't filter the transcripts yet, but it's a good point and I'll work on this (trying to make it generable enough)

I don't know how much it will impact the segmentation, though. Maybe not so much, but we should try and see

**Comment by ctastad** [comment]
@quentinblampey I see you're actively working on the sopa2rc branch. Do you anticipate implementing qv filtering with the 2.0 release? If not, what would you advise as an upstream target for local modification to ensure ingestion of qv-filtered transcripts in all steps of the xenium workflow?

**Comment by quentinblampey** [comment]
Hi @ctastad, no, unfortunately, the qv filtering will not be in `sopa==2.0.0`...

What you can already do (although not really clean) is to directly filter the transcript dataframe of the SpatialData object before running the pipeline.

Sorry for not implementing the feature yet, I'm a little bit overloaded, but I still have it on my todo-list. To make it general, I think I'll add a column in the transcript dataframe indicating whether to filter the transcript or not, and this column will be automatically created when reading the raw data. Does it sound good?

**Comment by ctastad** [comment]
No worries at all. You're producing an abundance of great work, so we don't want to further burden you.

As an acceptable work around, we are actually generating filtered transcript files in the xenium output and temporarily making them available for ingestion by sopa. Here is our implementation of that if it is of interest. 


https://github.com/ChoBioLab/sopa/blob/master/workflow/config/filter-transcripts.py

https://github.com/ChoBioLab/sopa/blob/master/workflow/config/validate-transcripts.py

**Comment by quentinblampey** [comment]
Thanks @ctastad for sending this!
I hope to be able to work on this feature soon :)

**Comment by quentinblampey** [comment]
Actually, I found out that only a minor change (2 lines) was needed for this feature, so I implemented it right now. Sorry for not having worked on this earlier...

To make it general, the only thing needed is to create a new column called `"low_quality_transcript"` in the `transcripts` dataframe. These transcripts will not be used during segmentation, but they will still be contained in the full dataframe (no data loss).

For instance, for Xenium data, you can do the following to keep transcripts with a QV higher than 20. Note that this operation is instantaneous, since it doesn't actually create the column, but only create a "lazy" column.

```python
sdata = sopa.io.xenium("/path/to/data")

df = sdata["transcripts"]
df["low_quality_transcript"] = df.qv >= 20

# continue with sopa, for instance saving your sdata object, and then running baysor
...
```

This will be available (and documented) in the next release, but you can already try it on the master branch!
