### ISSUE TITLE
Steps to use APIs

### ISSUE THREAD

**Issue by justinesjw** [gustaveroussy/sopa#9]
Hi, 

Thank you for building this tool! I'm very excited to implement it. 

I might have missed this but may I know where can I find the tutorial on steps to use the APIs? 
Do I sequentially implement these functions?
![image](https://github.com/gustaveroussy/sopa/assets/26448066/7e72f7f2-75cb-4b75-bf1c-22d1cbd8f054)

I've tried cross comparing the steps in CLI but failed to match the function names. 
Would really appreciate your help on this!

Thank you, 
Justine

**Comment by quentinblampey** [comment]
Hello @justinesjw,

Thanks for your interest in Sopa :)

For now, I only provide a documentation of the API. I will add in the next few weeks some tutorials on how to use the `sopa.stats` functions for instance, but I'm not sure to provide a tutorial for every API function because I thought most users may prefer using the CLI (or directly the Snakemake pipeline).

A few questions to understand what you want to do (this will help me to really answer your question and improve the documentation):
- Why do you prefer using the API rather than the CLI or Snakemake pipeline?
- What kind of segmentation to you want to perform (Cellpose? Baysor? Custom segmentation?)
- In which steps of Sopa (if not all) are you interest in? According to the illustration of the pipeline here: https://gustaveroussy.github.io/sopa/
- Are you familiar with the `spatialdata` library?

Thanks

**Comment by justinesjw** [comment]
Hello @quentinblampey, 

Thanks for your reply. :) Awesome! Excited for your tutorials. Will try out Snakemake pipeline! 

Regarding the questions: 
Q1 : As I am more familiar with R and Python I would prefer API over CLI. Also, for documentation purposes, I'm interested in a library which can streamline my scripts. Currently, I am running Baysor on it's own.

Q2/3 : I am interested in cell segmentation and do not have any preference on methods. Similar to most, I noticed that the default Xenium segmentation mis-segment a high portion of cells and would like to see how other methods perform? I am also excited to use your explorer function!

Q4 : My analyses are heavier on R packages though I am starting to use Squidpy which helped me understand `spatialdata` structures. 

Thanks! 

Best, 
Justine

**Comment by quentinblampey** [comment]
Hello @justinesjw,

Thanks for your answers, I better understand your usage now! Indeed, if you want to include Sopa into your own scripts, then the API is the best way to go. I just wanted to make sure that this was what you wanted (because the snakemake pipeline or the CLI are usually the first choices).

I finally released version `1.0.2` with the new [tutorial on the API usage](https://gustaveroussy.github.io/sopa/tutorials/api_usage/). I will be happy to improve this tutorial based on your feedback!

**Comment by quentinblampey** [comment]
Hello @justinesjw, have you had a chance to look at the tutorials?
If you have some questions, I'll be happy to help, and I can update the API tutorial. Else, if everything is clear, let me know if I can close the issue!

**Comment by justinesjw** [comment]
Hey @quentinblampey,

Thanks for the tutorials, they were helpful and informative! 
I'm still exploring among platforms! 

I'll close this issue for now.

**Comment by quentinblampey** [comment]
Ok great! Don't hesitate to re-open it in the future if you have new questions 🙂
